version: "3.9"

services:
  test_db:
    container_name: "test_db"
    image: mysql:8.0
    restart: always
    env_file:
      - ./test_env
    ports:
      - "3306:3306"
    volumes:
      - shop-test-mysql:/var/lib/mysql
    networks:
      - shop_network

  test:
    container_name: "shop_api-test"
    depends_on:
      - test_db
    env_file:
      - ./test_env
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - shop-api-test:/var/lib/api
    networks:
      - shop_network
    entrypoint: ["bash", "-c", "pytest --verbose --junitxml=test-results/junitxml/test_results.xml ./tests/api_tests"]
networks:
  shop_network:
    external: true
volumes:
  shop-test-mysql:
  shop-api-test: