version: "3.9"

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOSTNAME: db
    ports:
      - "3306:3306"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
networks:
  default:
    external:
      name: shop-network